ARGoS README
=============
:Author: Carlo Pinciroli
:Maintainer: Francesco Refolli
:Email:  francesco.refolli@gmail.com
:Date:   Sat 28 Jun 2024

What is ARGoS?
---------------

ARGoS is a physics-based simulator designed to simulate large-scale robot
swarms. Benchmark results show that ARGoS can perform physics-accurate
simulation involving thousands of robots in a fraction of real time.
ARGoS' main features are:

* Multi-threaded and deeply modular architecture, more flexible than any
  simulator with equivalent features;
* The possibility to run multiple physics engines at the same time;
* The possibility to divide the physical space in region, and assign different
  regions to different physics engines.

Starting from version 3, ARGoS is released under the terms of the MIT license.

Compiling ARGoS
---------------

Starting from version 3.0.1 Meson is used instead of CMake. The full list of requirements varies with your distro.

[options="header"]
|====================================================================================================================
| Distro | Packages
| OpenSUSE | gcc gcc-c++ pkgconf meson freeglut-devel libXmu-devel libXi-devel qt6-base-devel libfreeimage3 libfreeimageplus3 freeimage-devel lua lua-devel
| Fedora | gcc gcc-c++ pkgconf meson freeglut-devel libXmu-devel libXi-devel qt6-qtbase-devel freeimage freeimage-plus freeimage-devel lua lua-devel
| Arch Linux | freeglut freeimage gcc-libs glibc glu libglvnd libxi libxmu lua qt6-base meson
|====================================================================================================================

Other distros can run ARGoS but their requirements list is up to you. Feel free to contribute with it.

Packaging ARGoS
----------------

Installing ARGoS with the distro's package manager is suggested. In that case in one command you can build and package it.
As before not all distros are supported but feel free to contribute.

[options="header"]
|====================================================================================================================
| Distro | Packages
| OpenSUSE | ./package.sh opensuse
| Fedora | ./package.sh fedora
| Arch Linux | ./package.sh arch
|====================================================================================================================
